import { Pool } from "@/types/poolsTypes";

export const allPools: Pool[] = [
  {
    id: "1",
    name: "Аквадемия",
    coordinates: [55.66076, 37.54356],
    district: "ЮЗАО",
    metroStation: ["Калужская, Воронцовская, Новые Черемушки"],
    address: "ул. Профсоюзная, д. 76",
    ageGroups: ["0-1", "1-3", "3-5"],
    priceRange: { individual: 1500, group: 1000, trial: 800 },
    services: [
      "Индивидуальные занятия",
      "Групповые занятия",
      "Гидро реабилитация",
      "Занятия мама + малыш",
      "Аква-йога",
    ],
    description:
      "«Академия плавания» — это бассейн, который специализируется на занятиях плаванием для детей всех возрастов. В бассейне есть два отдельных бассейна, в которых одновременно могут заниматься несколько тренеров с детьми.",
    images: ["/images/akademy.webp"],
    schedule: "09:00 - 21:00",
    rating: 4.8,
    reviews: [
      { author: "Мария Иванова", comment: "Прекрасное место!", rating: 5 },
      { author: "Олег Петров", comment: "Дети в восторге.", rating: 4 },
    ],
  },
  {
    id: "2",
    name: "Китенок Юг",
    coordinates: [55.741244, 37.608423],
    district: "south",
    metroStation: ["Красная Пресня"],
    address: "ул. Ленина, д. 15",
    ageGroups: ["1-3", "3-5"],
    priceRange: { individual: 1800, group: 1300, trial: 1000 },
    description: "Идеально подходит для обучения плаванию малышей.",
    images: ["/images/kiteonok.webp"],
    schedule: "09:00 - 21:00",
    rating: 4.5,
    services: [
      "Индивидуальные занятия",
      "Групповые занятия",
      "Гидро реабилитация",
      "Занятия для взрослых",
      "Занятия мама + малыш",
      "Аква-йога",
    ],
    reviews: [
      {
        author: "Ирина Смирнова",
        comment: "Очень хорошие тренеры!",
        rating: 5,
      },
    ],
  },
  {
    id: "3",
    name: "Бассейн Лазурный",
    coordinates: [55.761244, 37.628423],
    district: "north",
    metroStation: ["Киевская"],
    address: "пр. Победы, д. 25",
    ageGroups: ["0-1", "1-3"],
    priceRange: { individual: 2000, trial: 1000 },
    description: "Чистый бассейн с профессиональными инструкторами.",
    images: ["/images/akademy.webp"],
    services: [
      "Индивидуальные занятия",
      "Групповые занятия",
      "Гидро реабилитация",
      "Занятия для взрослых",
      "Занятия мама + малыш",
      "Аква-йога",
      "Массаж",
    ],
    schedule: "07:00 - 23:00",
    rating: 4.7,
    reviews: [
      { author: "Анна Крылова", comment: "Удобный график занятий.", rating: 5 },
    ],
  },
  {
    id: "4",
    name: "Аквапарк Веселый Дельфин",
    coordinates: [55.751244, 37.628423],
    district: "center",
    metroStation: ["Тверская"],
    address: "ул. Зеленая, д. 7",
    ageGroups: ["3-5", "5-8"],
    priceRange: { individual: 2500, group: 1800 },
    description: "Большой выбор групповых программ.",
    images: ["/images/kiteonok.webp"],
    schedule: "08:00 - 20:00",
    rating: 4.6,
    services: ["Индивидуальные занятия", "Групповые занятия"],
    reviews: [
      { author: "Евгений Попов", comment: "Детям очень нравится!", rating: 4 },
    ],
  },
  {
    id: "5",
    name: "Малыш и вода",
    coordinates: [55.761244, 37.608423],
    district: "north",
    metroStation: ["Охотный ряд"],
    address: "ул. Морская, д. 3",
    ageGroups: ["0-1", "1-3"],
    priceRange: { individual: 1600, trial: 1200 },
    description: "Отлично оборудованный бассейн для самых маленьких.",
    images: ["/images/akademy.webp"],
    schedule: "10:00 - 20:00",
    services: ["Индивидуальные занятия", "Групповые занятия"],
    rating: 4.4,
    reviews: [
      {
        author: "Людмила Фомина",
        comment: "Ребенку очень нравится тренер!",
        rating: 5,
      },
    ],
  },
  {
    id: "6",
    name: "Аква-Пупс",
    coordinates: [55.832879, 37.662102],
    district: "north",
    metroStation: ["Ростокино"],
    address: "ул. Бажова, д. 8",
    ageGroups: ["0-1", "1-3"],
    priceRange: { individual: 1600, trial: 600 },
    description: "Отлично оборудованный бассейн для самых маленьких.",
    images: ["/images/akademy.webp"],
    schedule: "10:00 - 20:00",
    services: [
      "Индивидуальные занятия",
      "Групповые занятия",
      "Гидро реабилитация",
      "Занятия для взрослых",
    ],
    rating: 4.9,
    reviews: [
      {
        author: "Людмила Фомина",
        comment: "Ребенку очень нравится тренер!",
        rating: 5,
      },
    ],
  },
];
